[build]
  # This tells Netlify where to find your files and how to build them
  command = "npm install && npm run build"
  publish = "dist"

[functions]
  # This tells Netlify where your Stripe "brain" (create-checkout.js) lives
  directory = "netlify/functions"
  node_runtime = "nodejs20.x"

[[redirects]]
  # This ensures that refreshing the page doesn't give a 404 error
  from = "/*"
  to = "/index.html"
  status = 200
